scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus.docker.localhost']
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['reverse-proxy.poe-market.docker.localhost:8080']
  dns_sd_configs:
  - names:
    - 'prometheus.docker.localhost'
    - 'reverse-proxy.poe-market.docker.localhost'
    - ''
    type: 'A'
    port: 9323
